{{- define "common.deployment" -}}
{{- $common := dict "Values" .Values.common -}}  
{{- $noCommon := omit .Values "common" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $overrides $common -}}
{{- $replicaCount := .Values.replicaCount | default .Values.global.replicaCount -}}
# end voodoo
apiVersion: apps/v1
kind: Deployment
{{ template "common.metadata" . }} 
spec:
  minReadySeconds: {{ .Values.minReadySeconds | default .Values.global.minReadySeconds }}
  replicas: {{ $replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: {{ mul $replicaCount  2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- if (coalesce .Values.priorityClassName .Values.global.priorityClassName) }}
      priorityClassName: {{ (coalesce .Values.priorityClassName .Values.global.priorityClassName) }}
    {{- end }}
      imagePullSecrets:
        - name: {{ .Values.ImagePullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: appsettings
              mountPath: /app/appsettings
            {{- include "dpapi_volume_mount" . | indent 12 }}
          {{- range $volume := .Values.additionalVolumes }}
            - name: {{ $volume.name }}
              mountPath: {{ $volume.mountPath }}
           {{- end }}
          livenessProbe:
          {{- if .Values.global.LivenessProbe }}
            {{- toYaml .Values.global.LivenessProbe | nindent 12 }}
          {{- else }}
            httpGet:
              path: /health/statuscode
              port: http
          {{- end }}
            initialDelaySeconds: 5
            timeoutSeconds: 60
            periodSeconds: 90
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
          {{- if .Values.global.ReadinessProbe }}
            {{- toYaml .Values.global.ReadinessProbe | nindent 12 }}
          {{- else }}
            httpGet:
              path: /health
              port: http
          {{- end }}
            initialDelaySeconds: 5
            timeoutSeconds: 60
            periodSeconds: 30
            failureThreshold: 5
            successThreshold: 1
          resources:
            {{- toYaml (default .Values.global.resources  .Values.resources  )   | nindent 12 }}
          env:
          - name: ClientStateName
            value: {{ .Values.global.ClientStateName | quote }}
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ .Values.global.Environment | quote }}
          - name: APPSETTINGS_LOCATION
            value: "/app/appsettings" 
          - name: APPSETTING_LOCATION
            value: "/app/appsettings"
          {{- include "dpapi_key_location" . | indent 10 }}
          {{- if .Values.LoggingKey }}
          - name: Serilog__WriteTo__0__Args__apiKey
            value: {{ .Values.LoggingKey | quote }}{{ end }}
          - name: DoNotRequireHttps
            value: "true"
          {{- range $key, $val := .Values.additional_env_vars }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end}}
      volumes:
        - name: appsettings
          configMap:
            name: {{ include "common.appsettings.name" . }}
        {{- include "dpapi_secret_volume" .  | indent 8 }}
      {{- range $volume := .Values.additionalVolumes }}
        - name: {{ $volume.name }}
          {{ $volume.type -}}:
            name: {{ tpl $volume.configMapName $ }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
{{- end -}}
