{{- define "common.hpa" -}}
{{- $common := dict "Values" .Values.common -}}  
{{- $noCommon := omit .Values "common" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $overrides $common -}}
{{- if .Values.global.horizontalPodAutoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
{{ template "common.metadata" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.name" . }}
  minReplicas: {{ .Values.global.horizontalPodAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.global.horizontalPodAutoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.global.horizontalPodAutoscaling.targetCPUUtilizationPercentage }}
{{ end }}
{{ end }}
{{ end }}
